INSERT INTO activity_feed (
    actor_user_id,
    activity_type,
    entity_type,
    entity_id,
    group_id,
    event_id,
    title,
    message,
    image_url,
    visibility,
    metadata,
    created_at
)
VALUES
(
    NULL,
    'event_created',
    'event',
    1,
    NULL,
    1,
    'New event created',
    'A new Blue Mountains adventure event was added.',
    NULL,
    'public',
    '{"icon":"calendar-plus","color":"primary"}',
    NOW() - INTERVAL '5 minutes'
),
(
    NULL,
    'photo_uploaded',
    'group',
    2,
    2,
    NULL,
    'New photos posted',
    'Someone added photos to a public hiking group.',
    '/assets/images/feed/dummy-photo.png',
    'public',
    '{"icon":"camera","color":"warning"}',
    NOW() - INTERVAL '15 minutes'
),
(
    NULL,
    'comment_created',
    'event',
    1,
    NULL,
    1,
    'New comment',
    'A member commented on an upcoming event.',
    NULL,
    'public',
    '{"icon":"comment","color":"success"}',
    NOW() - INTERVAL '25 minutes'
),
(
    NULL,
    'group_created',
    'group',
    3,
    3,
    NULL,
    'New public group',
    'A new outdoor adventure group was created.',
    NULL,
    'public',
    '{"icon":"users","color":"info"}',
    NOW() - INTERVAL '45 minutes'
),
(
    NULL,
    'member_joined',
    'group',
    2,
    2,
    NULL,
    'New member joined',
    'A member joined a public group.',
    NULL,
    'public',
    '{"icon":"user-plus","color":"primary"}',
    NOW() - INTERVAL '1 hour'
);

